// Ortak soru bankası — karisik-tekrar.html ve sinav.html birlikte kullanır.
// Her soru: k=konu, s=soru metni, c=şıklar, d=doğru şık indeksi, a=nedenli açıklama.
// Matematiksel doğruluk elle hesaplanarak doğrulanmıştır.
window.SORU_BANKASI = [
 {k:"Çarpanlar",s:"60 sayısının asal çarpan gösterimi hangisi?",c:["2²×3×5","2×3×10","4×15"],d:0,a:"60=2×2×3×5. 10 ve 15 asal değildir, dallanmaya devam edilir."},
 {k:"Çarpanlar",s:"EBOB(24,36) kaçtır?",c:["12","6","72"],d:0,a:"24=2³×3, 36=2²×3². Ortak asalların küçük üsleri: 2²×3=12. 72 ise EKOK'tur."},
 {k:"Üslü İfadeler",s:"2⁵ × 2³ işleminin sonucu hangisine eşittir?",c:["2⁸","2¹⁵","4⁸"],d:0,a:"Tabanlar aynıysa üsler toplanır: 5+3=8. Üsler çarpılmaz, tabanlar da çarpılmaz."},
 {k:"Üslü İfadeler",s:"0,00042 sayısının bilimsel gösterimi?",c:["4,2×10⁻⁴","42×10⁻⁵","4,2×10⁴"],d:0,a:"Katsayı 1≤a<10 olmalı: 4,2. Virgül 4 basamak sağa gitti → 10⁻⁴."},
 {k:"Karekök",s:"√50 ifadesinin a√b biçimi hangisi?",c:["5√2","2√5","25√2"],d:0,a:"50=25×2 → √50=√25×√2=5√2."},
 {k:"Karekök",s:"√30 hangi iki doğal sayı arasındadır?",c:["5 ile 6","4 ile 5","6 ile 7"],d:0,a:"5²=25 < 30 < 36=6². Yani 5 ile 6 arasında."},
 {k:"Veri Analizi",s:"5, 7, 7, 9, 12 verisinin medyanı (ortanca) kaçtır?",c:["7","9","8"],d:0,a:"Sıralı 5 elemanın ortasındaki (3.) değer 7'dir. 8 aritmetik ortalamadır."},
 {k:"Veri Analizi",s:"Hangi grafik, bütünün parçalarını göstermek için en uygundur?",c:["Daire grafiği","Çizgi grafiği","Histogram"],d:0,a:"Daire grafiği yüzde/pay gösterir. Çizgi zamana bağlı değişim, histogram gruplandırılmış veri içindir."},
 {k:"Olasılık",s:"Bir zar atılıyor. Asal sayı gelme olasılığı kaçtır?",c:["3/6","2/6","4/6"],d:0,a:"Zarda asallar: 2, 3, 5 → 3 tane. Olasılık 3/6=1/2. (1 asal değildir!)"},
 {k:"Olasılık",s:"Bir torbada 3 kırmızı, 5 mavi top var. Kırmızı çekme olasılığı?",c:["3/8","3/5","5/8"],d:0,a:"Toplam 8 top, istenen 3 → 3/8. Payda her zaman TÜM durumlardır."},
 {k:"Cebir",s:"(x+3)² özdeşliğinin açılımı hangisi?",c:["x²+6x+9","x²+9","x²+3x+9"],d:0,a:"(a+b)²=a²+2ab+b². Orta terim 2·x·3=6x unutulmaz!"},
 {k:"Cebir",s:"x²−16 ifadesinin çarpanlara ayrılmış hâli?",c:["(x−4)(x+4)","(x−4)²","(x−8)(x+2)"],d:0,a:"İki kare farkı: a²−b²=(a−b)(a+b). 16=4²."},
 {k:"Denklemler",s:"3x−7=8 denkleminde x kaçtır?",c:["5","3","15"],d:0,a:"3x=15 → x=5. Önce sabit karşıya atılır, sonra bölünür."},
 {k:"Denklemler",s:"y=2x+1 doğrusunun eğimi kaçtır?",c:["2","1","3"],d:0,a:"y=mx+n biçiminde m eğimdir → 2. Sabit terim 1, y eksenini kestiği yerdir."},
 {k:"Eşitsizlikler",s:"−2x > 6 eşitsizliğinin çözümü hangisi?",c:["x < −3","x > −3","x < 3"],d:0,a:"Negatifle bölünce eşitsizlik YÖN DEĞİŞTİRİR: x < −3. En sık yapılan hata!"},
 {k:"Eşitsizlikler",s:"'En az 12' ifadesinin matematik dili hangisi?",c:["x ≥ 12","x > 12","x ≤ 12"],d:0,a:"'En az' alt sınırı DAHİL eder → ≥. 'den fazla' olsaydı > olurdu."},
 {k:"Üçgenler",s:"Kenarları 3, 4, 5 olan üçgen için hangisi doğrudur?",c:["Dik üçgendir","Eşkenar üçgendir","Üçgen oluşmaz"],d:0,a:"3²+4²=9+16=25=5² → Pisagor sağlanır, dik üçgendir."},
 {k:"Üçgenler",s:"Bir üçgende iki kenar 5 ve 9 ise üçüncü kenar hangisi OLAMAZ?",c:["14","6","10"],d:0,a:"Üçüncü kenar |9−5|=4 ile 9+5=14 ARASINDA olmalı (uçlar hariç). 14 olamaz."},
 {k:"Benzerlik",s:"Benzerlik oranı 2/3 olan üçgenlerde küçüğün çevresi 12 ise büyüğünki kaç?",c:["18","8","24"],d:0,a:"Çevreler de benzerlik oranındadır: 12÷(2/3)=18."},
 {k:"Benzerlik",s:"Eş üçgenler için hangisi her zaman doğrudur?",c:["Alanları eşittir","Sadece açıları eşittir","Kenarları orantılıdır ama eşit değildir"],d:0,a:"Eşlik = tüm kenar ve açılar eşit → alanlar da eşit. Benzerlikte ise oran vardır."},
 {k:"Dönüşüm",s:"A(3,−2) noktasının x eksenine göre yansıması hangisi?",c:["(3,2)","(−3,−2)","(−3,2)"],d:0,a:"x eksenine göre yansımada x aynı kalır, y işaret değiştirir."},
 {k:"Dönüşüm",s:"Bir şekil 5 birim sağa ötelenirse hangisi değişir?",c:["Konumu","Boyutu","Açıları"],d:0,a:"Öteleme sadece konum değiştirir; boyut, açı ve biçim korunur."},
 {k:"Cisimler",s:"Taban yarıçapı 3, yüksekliği 5 olan silindirin hacmi kaç π'dir?",c:["45π","30π","15π"],d:0,a:"V=πr²h=π×9×5=45π. Önce yarıçapın KARESİ alınır."},
 {k:"Cisimler",s:"Bir dik prizmanın hacmi neye eşittir?",c:["Taban alanı × yükseklik","Taban çevresi × yükseklik","Tüm yüzey alanları toplamı"],d:0,a:"Hacim = taban alanı × yükseklik. Çevre×yükseklik yanal alanı verir."},
 {k:"Çarpanlar",s:"İki asal sayının EBOB'u kaçtır? (sayılar farklı)",c:["1","2","Kendileri"],d:0,a:"Farklı asalların ortak çarpanı yoktur → EBOB=1. Böyle sayılara aralarında asal denir."},
 {k:"Çarpanlar",s:"EKOK(12,18) × EBOB(12,18) çarpımı neye eşittir?",c:["12×18","12+18","EKOK²"],d:0,a:"İki sayının EKOK×EBOB çarpımı her zaman sayıların çarpımına eşittir: 36×6=216=12×18."},
 {k:"Üslü İfadeler",s:"(2³)⁴ işleminin sonucu hangisi?",c:["2¹²","2⁷","8⁴"],d:0,a:"Üssün üssü alınırken üsler ÇARPILIR: 3×4=12. Toplanmaz!"},
 {k:"Üslü İfadeler",s:"5⁰ + 3⁻¹ işleminin sonucu kaçtır?",c:["4/3","1/3","0"],d:0,a:"5⁰=1 (sıfırıncı kuvvet 1'dir), 3⁻¹=1/3 → 1+1/3=4/3."},
 {k:"Karekök",s:"3√2 + 5√2 işleminin sonucu hangisi?",c:["8√2","8√4","15√2"],d:0,a:"Kök içleri aynıysa katsayılar toplanır: 3+5=8 → 8√2. Kökler çarpılmaz!"},
 {k:"Karekök",s:"√12 × √3 işleminin sonucu kaçtır?",c:["6","√15","36"],d:0,a:"Çarpımda kök içleri çarpılır: √36=6. Toplama sanıp √15 yapma!"},
 {k:"Veri Analizi",s:"8, 3, 5, 12, 7 verisinin açıklığı kaçtır?",c:["9","5","7"],d:0,a:"Açıklık = en büyük − en küçük = 12−3 = 9."},
 {k:"Veri Analizi",s:"Bir sınıfın not ortalaması 70. Herkese 5 puan eklenirse ortalama ne olur?",c:["75","70","72,5"],d:0,a:"Her veriye sabit eklenirse ortalama da o kadar artar: 70+5=75."},
 {k:"Olasılık",s:"Bir madeni para 2 kez atılıyor. İkisinin de tura gelme olasılığı?",c:["1/4","1/2","2/4"],d:0,a:"Bağımsız olaylar çarpılır: 1/2 × 1/2 = 1/4. (TT, TY, YT, YY → 4 durumdan 1'i)"},
 {k:"Olasılık",s:"Kesin olayın olasılığı kaçtır?",c:["1","0","1/2"],d:0,a:"Kesin olay mutlaka gerçekleşir → olasılığı 1. İmkânsız olay 0'dır."},
 {k:"Cebir",s:"x²+8x+16 ifadesi hangisinin açılımıdır?",c:["(x+4)²","(x+8)²","(x+2)(x+8)"],d:0,a:"Tam kare: orta terim 2·x·4=8x, sabit 4²=16 → (x+4)²."},
 {k:"Cebir",s:"3(2x−4) ifadesinin eşiti hangisi?",c:["6x−12","6x−4","5x−7"],d:0,a:"Dağılma: 3 HER terimle çarpılır: 3·2x−3·4=6x−12."},
 {k:"Denklemler",s:"x/3 + 2 = 7 denkleminde x kaçtır?",c:["15","5","27"],d:0,a:"x/3=5 → x=15. Önce 2 karşıya, sonra 3 ile çarp."},
 {k:"Denklemler",s:"(2,5) noktası hangi doğrunun üzerindedir?",c:["y=2x+1","y=x+2","y=3x"],d:0,a:"x=2 koy: 2·2+1=5 ✓. Diğerlerinde 4 ve 6 çıkar, 5 değil."},
 {k:"Eşitsizlikler",s:"x ≤ 3 eşitsizliğinin sayı doğrusunda gösteriminde 3'te hangi işaret olur?",c:["Dolu nokta","Boş nokta","Ok işareti"],d:0,a:"≤ sınırı DAHİL eder → dolu (içi boyalı) nokta. < olsaydı boş nokta."},
 {k:"Eşitsizlikler",s:"5 − x > 2 eşitsizliğinin çözümü hangisi?",c:["x < 3","x > 3","x < −3"],d:0,a:"−x > −3 → negatifle çarpınca yön değişir: x < 3."},
 {k:"Üçgenler",s:"Dik üçgende dik kenarlar 6 ve 8 ise hipotenüs kaçtır?",c:["10","14","7"],d:0,a:"6²+8²=36+64=100 → √100=10. (3-4-5'in 2 katı)"},
 {k:"Üçgenler",s:"Bir üçgende büyük açının karşısında ne bulunur?",c:["En uzun kenar","En kısa kenar","Her zaman hipotenüs"],d:0,a:"Açı-kenar ilişkisi: büyük açının karşısında büyük kenar. Hipotenüs sadece dik üçgende var."},
 {k:"Benzerlik",s:"Benzerlik oranı 1/3 olan iki üçgende büyüğün bir kenarı 15 ise küçüğün karşılık kenarı?",c:["5","45","12"],d:0,a:"Küçük/büyük=1/3 → 15×1/3=5."},
 {k:"Benzerlik",s:"İki üçgenin benzer olması için en az kaç açısının eşit olması yeterlidir?",c:["2","3","1"],d:0,a:"AA benzerliği: 2 açı eşitse üçüncü de eşittir (iç açılar 180°)."},
 {k:"Dönüşüm",s:"A(−1,4) noktası orijin etrafında 180° döndürülürse görüntüsü?",c:["(1,−4)","(−1,−4)","(4,−1)"],d:0,a:"180° dönmede iki koordinat da işaret değiştirir: (1,−4)."},
 {k:"Dönüşüm",s:"A(2,3) noktası y eksenine göre yansıtılırsa görüntüsü hangisi?",c:["(−2,3)","(2,−3)","(−2,−3)"],d:0,a:"y eksenine göre yansımada y aynı kalır, x işaret değiştirir."},
 {k:"Cisimler",s:"Ayrıt uzunluğu 4 cm olan küpün yüzey alanı kaç cm²'dir?",c:["96","64","48"],d:0,a:"Küpün 6 eş kare yüzü var: 6×4²=6×16=96. 64 hacimdir!"},
 {k:"Cisimler",s:"Silindirin yanal yüzeyi açıldığında hangi şekil oluşur?",c:["Dikdörtgen","Daire","Üçgen"],d:0,a:"Yanal yüz açılınca dikdörtgen: bir kenarı taban çevresi (2πr), diğeri yükseklik."}
];
window.KONU_SAYFA = {"Çarpanlar":"1-carpanlar.html","Üslü İfadeler":"uslu-ifadeler.html","Karekök":"karekok.html","Veri Analizi":"veri-analizi.html","Olasılık":"olasilik.html","Cebir":"cebir.html","Denklemler":"denklemler.html","Eşitsizlikler":"esitsizlikler.html","Üçgenler":"ucgenler.html","Benzerlik":"benzerlik.html","Dönüşüm":"donusum.html","Cisimler":"cisimler.html"};
